project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Chase Mathis"
  description: "Personal Website for Chase Mathis: Statistics and Computer Science Major at Duke University"
  site-url: "https://chasehmathis.github.io/"
  
  
  sidebar:
    background: "#393274"
    
    
    style: docked
    search: true
    collapse-level: 1
    contents: 
      - section: "About Me"
        contents: 
          - href: AboutMe/Resume.pdf
            text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto




