project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Chase Mathis"
  description: "Personal Website for Chase Mathis: Statistics and Computer Science Major at Duke University"
  site-url: "https://chasehmathdis.github.io/"
  
  
  navbar:
    background: "#148F77"
    style: docked
    search: true
    left:
      - text: "Home"
        file: index.qmd

            

format:
  html:
    theme: cosmo
    css: style/styles.css
    linkcolor: "#148F77"
    toc: true
    
execute:
  freeze: auto




