---
title: "Why do Math/Stat Research"
output: html_document
bibliography: references.bib
execute:
  echo: false
warning: false
message: false
error: false
editor:
  markdown:
    wrap: 72
---

I'm (re-)reading Infinite Jest and was struck by the line: "Hal tends to
know way less about why he feels certain ways about the objects and
pursuits he's devoted to than he does about the objects and pursuits
themselves." If there has been any positive effect of AI on humanity it
is that it has forced many of us (especially young people) to ask why I
feel the way I do about our pursuits. The future has never been more
uncertain, so what am I doing and why am I doing it? Outside the walls
of academia my friends are no less likely to be asking these questions.
However, only I inside the walls of academia can spend the afternoon
writing about it without their boss getting upset[^1].

[^1]: In fact, I could argue this is beneficial to my work.

The year is 2150. We have the technology to explore the universe.
Recall, the universe is 99.99...% nothing. So most ships that embark out
don't find much and the space exploration industry is delegated to
universities whose work is funded by taxpayers. It takes a relatively
rare skillset to work on these exploration ships. Some children have
this skillset (either by nature or nurture) and are put in special
programs: accelerated classes, summer schools, clubs, and selective
universities. All these talented kids are interested in exploring the
universe (I mean how could you not be), but also nobody can do this job
except for these kids.

After a seemingly 30 year long training program, the students get to
lead the ships, training younger students as they go out and explore the
universe. At the start of the space exploration industry, captains that
found something could name it after themselves, but it is less often
now[^2]. While the captains could get paid more doing work on Earth with
their relatively rare skills, they enjoyed exploring and working with
ultimate freedom.

[^2]: Mildly underdiscussed topic: what is the cause for the decline in
    naming theorems/models/architectures after the people? Two
    inklings: 1) Number of authors per work has increased. 2) Research
    papers must be packaged and sold now. Nobody wants to use the Mathis
    Model. But people want to use the *transformer* or *conformal
    inference* because it sounds cool/fancy.

One year ago in 2149 an AI was able to pass the hardest test space
explorers take[^3]. That is not real space exploration, the explorers
said, but just a toy test. Fine. Then in the last 6 months the AI has
been discovering stuff. An old famous explorer said there was nothing in
this area of space. Everybody agreed. Then two moths ago an AI found
something there[^4].

[^3]: IMO

[^4]: Unit Distance Conjecture

One year ago, I joined a ship as a trainee. It is a well known ship that
has found important stuff in the past and has good resources. I say this
to acknowledge my immense privilege and perhaps personally unique
perspective.

With all these AIs getting better at exploring, young trainees are
beginning to ask what am I doing and why am I doing it. I don't think I
ever had the opportunity to ask why I wanted to explore space. As I said
before: *how could you not want to*[^5]. I think that is what we all
tell ourselves. But one dark reason we all must admit is because, up
until a few years ago, nobody could do it besides us. Since we were kids
we've been trained for this position that few of our peers could do.
This is no longer the case. A second dark reason is because we want to
be remembered for the stuff we find. Even though we don't put our names
on stuff anymore, people in the know, know who found what. Institutions
and academies give awards to those people and hence they are remembered.

[^5]: That's not really an answer but a deflection. My real answer is
    that I need to know the bare truth. I need to know what is necessary
    and sufficient and more importantly why.

I apologize for the long allegory. But I think putting mathematical
research in this framing is helpful. I understand why researchers are
uneasy about AI in math. I think the community should be careful about
incentives and assigning credit and getting fair compensation[^6]. I
like this metaphor because it gives me optimism. If the AIs are good at
finding stuff: beautiful, simple, cross-disciplinary stuff how could you
not be happy. Explorers will still teach other explorers how the AI got
there and what tools it used[^7].

[^6]: I broadly agree with the Leiden Declaration and recommend signing
    it if you also agree <https://leidendeclaration.ai/>.

[^7]:For people that think AI will do this, I would say that is because
    humans failed rather than AI succeeded in this task.

I don't know where the future lies. Right now is the so-called
centaur era for AIs + human. But, it is difficult
to not believe that eventually (5, 10, 20, 50, 100 years) human explorers
will be net-negative and thus replaced. 


In this regime, I want to wrap up and say one more thing. The discoveries made completely by AI are
still made by humanity. When I read an interesting paper by a researcher,
I enjoy reading it because the topic is interesting and because I'm happy
that humanity produced something like this. There is a feeling one gets
that when AI disproves something like the unit distance conjecture that
somehow humanity did not do this. That instead some alien species
disproved this and humanity had no thumb on the scale. 
Indeed, no single author disproved the unit distance
conjecture. But it is not true that humanity had no role in this. AI did
not arrive from a different planet but was created on the back of
humanity.

I recently read a single author paper from the early 20th century on
some minimax results. That piece of work required the labor of one
person and a few others who he cites. Disproving the unit distance
conjecture required the labor of all deceased humans, manufacturers of
the chip, construction workers of the data centers, the power plants,
and from the AI researchers and engineers who coded tricks upon gradient descent. In
some regard, AI is a collective human intelligence. It's impossible to
write a paper with hundreds of co-authors. If you're citing an LLM
you're kind of citing humanity.

I will admit that a significant reason why I am in my Statistics PhD
is because I have been good at it. My ego would understandably prefer
that superintelligent AI had never arrived. But my soul—my 
5 year old self that would write powers of 2 on his bedroom wall wondering 
about the patterns that make up this universe—cannot wait to see what will come. 

